version: "2"
services:

    api:
        image: node:14
        volumes:
            - ./:/app
        working_dir: /app
        env_file:
            ./.env
        command: ["npm", "run", "start:dev"]
        ports:
            - "3000:3000"
        depends_on:
            - mongo

    mongo:
        image: mongo:3.6
        ports:
            - "27019:27017"
